### ISSUE TITLE
数据导入数据库报错

### ISSUE THREAD

**Issue by varSwift** [SleepySoft/StockAnalysisSystem_Deprecated#1]
hi,SleepySoft:
我叫胡迎宾，是一名学生，在个git上看见你这个项目，我刚学python，比较感兴趣。在我运行您的代码时会出现：AttributeError: 'ModuleData' object has no attribute 'Name'的错误。并且这句代码：result = self.__db_plug_in.Init('Data/Plug-in.db') and result；是不是需要一个Plug-in.db数据库文件，我没在您的项目中看见，还是说这个文件是这个项目运行的时候自动生成的？

期待您的回复，谢谢！

**Comment by SleepySoft** [comment]
应该没问题吧。你可以加我QQ：382251291. 备注一下。

varSwift <notifications@github.com> 于2018年1月3日周三 上午11:33写道：
